version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "semiannually"
    open-pull-requests-limit: 1
    groups:
      npm_and_yarn:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "semiannually"
    open-pull-requests-limit: 1
    groups:
      npm_and_yarn:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "semiannually"
    open-pull-requests-limit: 1
    groups:
      npm_and_yarn:
        patterns: ["*"]
