version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    groups:
      npm_and_yarn:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    groups:
      npm_and_yarn:
        patterns: ["*"]
