# The Docker image that will be used to build your app
image: node:18-alpine

# Functions that should be executed before the build script is run
before_script:
  - yarn install

# build:
#   stage: build
#   script: yarn build
#   rules:
#     # This ensures that only pushes to the default branch will trigger
#     # a pages deploy
#     - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

variables:
  - OPENAI_API_KEY: ${CI_ENVIRONMENT_SLUG}_OPENAI_API_KEY
  - GEMINI_MODEL_NAME: ${CI_ENVIRONMENT_SLUG}_GEMINI_MODEL_NAME
  - GEMINI_API_KEY_1: ${CI_ENVIRONMENT_SLUG}_GEMINI_API_KEY_1

pages:
  stage: build-and-deploy
  script:
    - yarn build
    - yarn start:prod
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
