import {
  LegalBulletList,
  LegalDefinitionList,
  LegalH5,
  LegalH6,
  LegalP,
  LegalSection,
  LegalSubtitle,
  legalWebsiteUrl,
} from "src/components/legal/LegalTypography";

export const PrivacyPolicyBody = () => (
  <>
    <LegalP>
      This Privacy Policy describes Our policies and procedures on the
      collection, use, and disclosure of your information when you use the
      Service and tells you about your privacy rights and how the law protects
      you.
    </LegalP>
    <LegalP>
      We use your Personal data to provide and improve the Service. By using
      the Service, you agree to the collection and use of information in
      accordance with this Privacy Policy.
    </LegalP>

    <LegalSection>
      <LegalH5>Interpretation and Definitions</LegalH5>
      <LegalH6>Interpretation</LegalH6>
      <LegalP>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </LegalP>
      <LegalH6>Definitions</LegalH6>
      <LegalDefinitionList
        items={[
          {
            term: "Account",
            description:
              "A unique account created for you to access Our Service or parts of Our Service.",
          },
          {
            term: "Affiliate",
            description:
              "An entity that controls, is controlled by or is under common control with a party.",
          },
          { term: "Company", description: "Refers to TalePod." },
          {
            term: "Cookies",
            description:
              "Small files placed on your computer or device by a website, containing the details of your browsing history on that website.",
          },
          { term: "Country", description: "Switzerland" },
          {
            term: "Device",
            description:
              "Any device that can access the Service such as a computer, a cellphone or a digital tablet.",
          },
          {
            term: "Personal Data",
            description:
              "Any information that relates to an identified or identifiable individual.",
          },
          {
            term: "Service",
            description: "Refers to the web application.",
          },
          {
            term: "Service Provider",
            description:
              "Any natural or legal person who processes the data on behalf of the Company.",
          },
          {
            term: "Usage Data",
            description:
              "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.",
          },
          {
            term: "Website",
            description: legalWebsiteUrl,
          },
          {
            term: "You",
            description:
              "The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.",
          },
        ]}
      />
    </LegalSection>

    <LegalSection>
      <LegalH5>Collecting and Using your Personal Data</LegalH5>
      <LegalH6>Types of Data Collected</LegalH6>
      <LegalSubtitle>Personal Data</LegalSubtitle>
      <LegalP>
        While using Our Service, We may ask you to provide Us with certain
        personally identifiable information that can be used to contact or
        identify you. Personally identifiable information may include, but is not
        limited to:
      </LegalP>
      <LegalBulletList
        items={["First name and last name", "Usage Data"]}
      />

      <LegalSubtitle>Usage Data</LegalSubtitle>
      <LegalP>Usage Data is collected automatically when using the Service.</LegalP>
      <LegalP>
        Usage Data may include information such as your Device's Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of Our Service that you visit, the time and date of your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </LegalP>
      <LegalP>
        When you access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited to,
        the type of mobile device you use, your mobile device unique ID, the IP
        address of your mobile device, your mobile operating system, the type of
        mobile Internet browser you use, unique device identifiers and other
        diagnostic data.
      </LegalP>
      <LegalP>
        We may also collect information that your browser sends whenever you
        visit Our Service or when you access the Service by or through a mobile
        device.
      </LegalP>

      <LegalSubtitle>Tracking Technologies and Cookies</LegalSubtitle>
      <LegalP>
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies used
        are beacons, tags, and scripts to collect and track information and to
        improve and analyze Our Service. The technologies We use may include:
      </LegalP>
      <LegalDefinitionList
        items={[
          {
            term: "Cookies or Browser Cookies",
            description:
              "A cookie is a small file placed on your Device. you can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent.",
          },
          {
            term: "Web Beacons",
            description:
              "Certain sections of Our Service and Our emails may contain small electronic files known as web beacons.",
          },
        ]}
      />
      <LegalP>
        Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
        remain on your personal computer or mobile device when you go offline,
        while Session Cookies are deleted as soon as you close your web browser.
      </LegalP>
    </LegalSection>
  </>
);
