services:
  production:
    # container_name: talepod-production
    image: talepod:latest
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    restart: always
    env_file:
      - .env
    # Enable this volume mapping if you want to test the production setup but without having to rebuild the docker container for every code change.
    # To update the frontend for this you will have to run docker-compose run --rm production yarn build
    # To update the code of the server you have to restart the production container
    #    volumes:
    #      - .:/talepod/
    command: yarn start:prod
    working_dir: /talepod-app
    ports:
      - 8080:8080

  # frontend:
  #   # container_name: talepod-frontend
  #   build:
  #     context: ..
  #     dockerfile: deploy/Dockerfile
  #     target: client-builder
  #   restart: always
  #   depends_on:
  #     - backend
  #   command: yarn start
  #   volumes:
  #     - .:/talepod/client/
  #   working_dir: /talepod/client
  #   ports:
  #     - 4000:4000

  # backend:
  #   # container_name: talepod-backend
  #   build:
  #     context: ..
  #     dockerfile: deploy/Dockerfile
  #     target: server-builder
  #   restart: always
  #   command: yarn start
  #   # volumes:
  #   #   - .:/public/server/
  #   # working_dir: /public/server/
  #   volumes:
  #     - .:/talepod//server
  #   working_dir: /talepod/server
  #   ports:
  #     - 4001:4001
