services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_PACKAGES_TOKEN: ${GITHUB_PACKAGES_TOKEN}
    ports:
      - "16001:16001"
    env_file:
      - ./.env
    environment:
      - PORT=16001
    restart: unless-stopped
