# # The Docker image that will be used to build your app
# image: node:18-alpine

# # Functions that should be executed before the build script is run
# before_script:
#   # - yarn install

# variables:
#   OPENAI_API_KEY: ${OPENAI_API_KEY}
#   GOOGLE_GEMINI_MODEL_NAME: ${GEMINI_MODEL_NAME}
#   GOOGLE_GEMINI_API_KEY_1: ${GEMINI_API_KEY_1}

# build-frontend:
#   stage: build
#   script:
#     - ls # List contents of current directory
#     - cd ./client
#     - pwd # Print current working directory
#     - yarn install
#     - yarn buildGOOGLE_

# build-backend:
#   stage: build
#   script:
#     - ls # List contents of current directory
#     - cd ./server
#     - pwd # Print current working directory
#     - yarn install
#     - yarn build
# # pages:
# #   stage: deploy
# #   script:
# #     - yarn build
# #     # - yarn start:prod
# #   publish: build
# #   artifacts:
# #     paths:
# #       # The folder that contains the files to be exposed at the Page URL
# #       - public
# #   rules:
# #     # This ensures that only pushes to the default branch will trigger
# #     # a pages deploy
# #     - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
