FROM node:16-alpine as builder

# # Expose these two ports as they are used by the app
# EXPOSE 4000-4001
# EXPOSE 8080

# ENV DIR /{PROJECT_NAME}

# RUN chown -R node.node /{PROJECT_NAME}

# # Tell docker that all future commands should run as the appuser user
# USER node

# LABEL maintainer="{PERSON_NAME} <{PERSON_EMAIL}>"

# COPY tsconfig.json .
# COPY package.json .
# COPY yarn.lock .
# RUN  yarn install
# # RUN yarn install --frozen-lockfile

# COPY web/public web/public
# COPY web/src web/src
# RUN  yarn build

# COPY server server

# CMD yarn start:prod
