import { BaseDataParams } from "src/models/types";
import { SupportedLanguages } from "../../utils/languages";

export const popularStories: BaseDataParams[] = [
  {
    language: SupportedLanguages.en,
    data: [
      "Goldilocks and the Three Bears",
      "The Ugly Duckling",
      "The Gruffalo by Julia Donaldson",
      "Goodnight Moon by Margaret Wise Brown",
      "The Tale of Peter Rabbit by Beatrix Potter",
      "The Very Hungry Caterpillar by Eric Carle",
      "Where the Wild Things Are by Maurice Sendak",
      "Winnie-the-Pooh by A.A. Milne",
      "The Little Engine That Could by Watty Piper",
      "Cinderella",
    ],
  },
  {
    language: SupportedLanguages.ar,
    data: [
      "علاء الدين والمصباح السحري (Aladdin and the Magic Lamp)",
      "سندباد البحري (Sindbad the Sailor)",
      "الأميرة شهرزاد (Princess Scheherazade)",
      "علي بابا والأربعون لصاً (Ali Baba and the Forty Thieves)",
      "النملة والجندب (The Ant and the Grasshopper)",
      "القرد والتمساح (The Monkey and the Crocodile)",
      "الراعي والذئب (The Shepherd and the Wolf)",
      "الصياد والمارد (The Fisherman and the Genie)",
      "الثعلب والغراب (The Fox and the Crow)",
      "الأسد والفأر (The Lion and the Mouse)",
    ],
  },
  {
    language: SupportedLanguages.es,
    data: [
      "Los Tres Cerditos (The Three Little Pigs)",
      "La Caperucita Roja (Little Red Riding Hood)",
      "El Patito Feo (The Ugly Duckling)",
      "Blancanieves (Snow White)",
      "La Bella Durmiente (Sleeping Beauty)",
      "Pinocho (Pinocchio)",
      "El Ratoncito Pérez",
      "La Sirenita (The Little Mermaid)",
      "Hansel y Gretel",
      "El Soldadito de Plomo (The Steadfast Tin Soldier)",
    ],
  },
  {
    language: SupportedLanguages.fr,
    data: [
      "Le Petit Chaperon Rouge (Little Red Riding Hood)",
      "La Belle et la Bête (Beauty and the Beast)",
      "Le Petit Prince by Antoine de Saint-Exupéry",
      "Cendrillon (Cinderella)",
      "Blanche-Neige et les Sept Nains (Snow White and the Seven Dwarfs)",
      "Le Chat Botté (Puss in Boots)",
      "Boucle d'Or et les Trois Ours (Goldilocks and the Three Bears)",
      "Barbe-Bleue (Bluebeard)",
      "Le Corbeau et le Renard (The Crow and the Fox)",
      "La Cigale et la Fourmi (The Grasshopper and the Ant)",
    ],
  },
  {
    language: SupportedLanguages.de,
    data: [
      "Die Bremer Stadtmusikanten (The Bremen Town Musicians)",
      "Rotkäppchen (Little Red Riding Hood)",
      "Der Froschkönig (The Frog King)",
      "Hänsel und Gretel",
      "Rumpelstilzchen",
      "Schneewittchen (Snow White)",
      "Das tapfere Schneiderlein (The Brave Little Tailor)",
      "Max und Moritz by Wilhelm Busch",
      "Der Struwwelpeter by Heinrich Hoffmann",
      "Der kleine Häwelmann by Theodor Storm",
    ],
  },
  {
    language: SupportedLanguages.pt,
    data: [
      "Os Três Porquinhos (The Three Little Pigs)",
      "Chapeuzinho Vermelho (Little Red Riding Hood)",
      "O Patinho Feio (The Ugly Duckling)",
      "A Bela e a Fera (Beauty and the Beast)",
      "Cinderela (Cinderella)",
      "Branca de Neve (Snow White)",
      "O Soldadinho de Chumbo (The Steadfast Tin Soldier)",
      "João e o Pé de Feijão (Jack and the Beanstalk)",
      "O Gato de Botas (Puss in Boots)",
      "A Lebre e a Tartaruga (The Hare and the Tortoise)",
    ],
  },
  {
    language: SupportedLanguages.it,
    data: [
      "Pinocchio by Carlo Collodi",
      "La Bella Addormentata (Sleeping Beauty)",
      "Cappuccetto Rosso (Little Red Riding Hood)",
      "Biancaneve e i Sette Nani (Snow White and the Seven Dwarfs)",
      "I Tre Porcellini (The Three Little Pigs)",
      "Il Gatto con gli Stivali (Puss in Boots)",
      "Hansel e Gretel",
      "La Sirenetta (The Little Mermaid)",
      "Il Principe Felice (The Happy Prince)",
      "Il Soldatino di Piombo (The Steadfast Tin Soldier)",
    ],
  },
  {
    language: SupportedLanguages.ja,
    data: [
      "桃太郎 (Momotaro, The Peach Boy)",
      "かぐや姫 (The Tale of the Bamboo Cutter)",
      "浦島太郎 (Urashima Taro)",
      "鶴の恩返し (The Crane’s Gratitude)",
      "花咲か爺さん (The Old Man Who Made Flowers Bloom)",
      "一寸法師 (The One-Inch Boy)",
      "さるかに合戦 (The Monkey and the Crab)",
      "竹取物語 (The Tale of Princess Kaguya)",
      "雪女 (The Snow Woman)",
      "おむすびころりん (Rolling Rice Balls)",
    ],
  },
  {
    language: SupportedLanguages.ko,
    data: [
      "흥부와 놀부 (Heungbu and Nolbu)",
      "해와 달이 된 오누이 (The Brother and Sister Who Became the Sun and the Moon)",
      "금도끼와 은도끼 (The Golden Axe and the Silver Axe)",
      "토끼와 거북이 (The Rabbit and the Turtle)",
      "호랑이와 곶감 (The Tiger and the Persimmon)",
      "콩쥐팥쥐 (Kongjwi and Patjwi)",
      "달님과 해님 (Moon and Sun)",
      "쥐 신랑 이야기 (The Mouse Bridegroom)",
      "선녀와 나무꾼 (The Fairy and the Woodcutter)",
      "장화홍련전 (The Story of Janghwa and Hongryeon)",
    ],
  },
  {
    language: SupportedLanguages.ru,
    data: [
      "Колобок (The Little Round Bun)",
      "Репка (The Turnip)",
      "Иван Царевич и Серый Волк (Ivan Tsarevich and the Grey Wolf)",
      "Морозко (Father Frost)",
      "Лиса и Журавль (The Fox and the Crane)",
      "Василиса Прекрасная (Vasilisa the Beautiful)",
      "Царевна-Лягушка (The Frog Princess)",
      "Аленький Цветочек (The Scarlet Flower)",
      "Снегурочка (The Snow Maiden)",
      "Маша и Медведь (Masha and the Bear)",
    ],
  },
  {
    language: SupportedLanguages.hi,
    data: [
      "पंचतंत्र की कहानियां (Panchatantra Stories)",
      "अकबर और बीरबल (Akbar and Birbal Tales)",
      "सिंह और चूहा (The Lion and the Mouse)",
      "कौआ और लोमड़ी (The Crow and the Fox)",
      "कछुआ और खरगोश (The Tortoise and the Hare)",
      "चालाक खरगोश (The Clever Rabbit)",
      "थIRSTY Crow",
      "गुडिया का सपना (The Doll’s Dream)",
      "लालच बुरी बला है (Greed is a Curse)",
      "दोस्ती की ताकत (Power of Friendship)",
    ],
  },
  {
    language: SupportedLanguages.zh_Hans,
    data: [
      "孟姜女的故事 (The Story of Meng Jiangnu)",
      "嫦娥奔月 (Chang’e Flies to the Moon)",
      "十二生肖的传说 (The Legend of the Chinese Zodiac)",
      "木兰辞 (Ballad of Mulan)",
      "井底之蛙 (The Frog at the Bottom of the Well)",
      "孔融让梨 (Kong Rong Gives Up the Bigger Pear)",
      "神笔马良 (The Magic Brush Ma Liang)",
      "三只小猪 (Three Little Pigs - Chinese Adaptation)",
      "龟兔赛跑 (The Tortoise and the Hare)",
      "大闹天宫 (The Monkey King)",
    ],
  },
];
