import { BaseDataParams } from "src/models/types";
import { SupportedLanguages } from "../../utils/languages";

export const popularStories: BaseDataParams[] = [
  {
    language: SupportedLanguages.en,
    data: [
      "Goldilocks and the Three Bears",
      "The Ugly Duckling",
      "The Gruffalo by Julia Donaldson",
      "Goodnight Moon by Margaret Wise Brown",
      "The Tale of Peter Rabbit by Beatrix Potter",
      "The Very Hungry Caterpillar by Eric Carle",
      "Where the Wild Things Are by Maurice Sendak",
      "Winnie-the-Pooh by A.A. Milne",
      "The Little Engine That Could by Watty Piper",
      "Cinderella",
    ],
  },
  {
    language: SupportedLanguages.ar,
    data: [
      "علاء الدين والمصباح السحري",
      "سندباد البحري",
      "الأميرة شهرزاد",
      "علي بابا والأربعون لصاً",
      "النملة والجندب",
      "القرد والتمساح",
      "الراعي والذئب",
      "الصياد والمارد",
      "الثعلب والغراب",
      "الأسد والفأر",
    ],
  },
  {
    language: SupportedLanguages.es,
    data: [
      "Los Tres Cerditos",
      "La Caperucita Roja",
      "El Patito Feo",
      "Blancanieves",
      "La Bella Durmiente",
      "Pinocho",
      "El Ratoncito Pérez",
      "La Sirenita",
      "Hansel y Gretel",
      "El Soldadito de Plomo",
    ],
  },
  {
    language: SupportedLanguages.fr,
    data: [
      "Le Petit Chaperon Rouge",
      "La Belle et la Bête",
      "Le Petit Prince by Antoine de Saint-Exupéry",
      "Cendrillon",
      "Blanche-Neige et les Sept Nains",
      "Le Chat Botté",
      "Boucle d'Or et les Trois Ours",
      "Barbe-Bleue",
      "Le Corbeau et le Renard",
      "La Cigale et la Fourmi",
    ],
  },
  {
    language: SupportedLanguages.de,
    data: [
      "Die Bremer Stadtmusikanten",
      "Rotkäppchen",
      "Der Froschkönig",
      "Hänsel und Gretel",
      "Rumpelstilzchen",
      "Schneewittchen",
      "Das tapfere Schneiderlein",
      "Max und Moritz by Wilhelm Busch",
      "Der Struwwelpeter by Heinrich Hoffmann",
      "Der kleine Häwelmann by Theodor Storm",
    ],
  },
  {
    language: SupportedLanguages.pt,
    data: [
      "Os Três Porquinhos",
      "Chapeuzinho Vermelho",
      "O Patinho Feio",
      "A Bela e a Fera",
      "Cinderela",
      "Branca de Neve",
      "O Soldadinho de Chumbo",
      "João e o Pé de Feijão",
      "O Gato de Botas",
      "A Lebre e a Tartaruga",
    ],
  },
  {
    language: SupportedLanguages.it,
    data: [
      "Pinocchio by Carlo Collodi",
      "La Bella Addormentata",
      "Cappuccetto Rosso",
      "Biancaneve e i Sette Nani",
      "I Tre Porcellini",
      "Il Gatto con gli Stivali",
      "Hansel e Gretel",
      "La Sirenetta",
      "Il Principe Felice",
      "Il Soldatino di Piombo",
    ],
  },
  {
    language: SupportedLanguages.ja,
    data: [
      "桃太郎",
      "かぐや姫",
      "浦島太郎",
      "鶴の恩返し",
      "花咲か爺さん",
      "一寸法師",
      "さるかに合戦",
      "竹取物語",
      "雪女",
      "おむすびころりん",
    ],
  },
  {
    language: SupportedLanguages.ko,
    data: [
      "흥부와 놀부",
      "해와 달이 된 오누이",
      "금도끼와 은도끼",
      "토끼와 거북이",
      "호랑이와 곶감",
      "콩쥐팥쥐",
      "달님과 해님",
      "쥐 신랑 이야기",
      "선녀와 나무꾼",
      "장화홍련전",
    ],
  },
  {
    language: SupportedLanguages.ru,
    data: [
      "Колобок",
      "Репка",
      "Иван Царевич и Серый Волк",
      "Морозко",
      "Лиса и Журавль",
      "Василиса Прекрасная",
      "Царевна-Лягушка",
      "Аленький Цветочек",
      "Снегурочка",
      "Маша и Медведь",
    ],
  },
  {
    language: SupportedLanguages.hi,
    data: [
      "पंचतंत्र की कहानियां",
      "अकबर और बीरबल",
      "सिंह और चूहा",
      "कौआ और लोमड़ी",
      "कछुआ और खरगोश",
      "चालाक खरगोश",
      "थIRSTY Crow",
      "गुडिया का सपना",
      "लालच बुरी बला है",
      "दोस्ती की ताकत",
    ],
  },
  {
    language: SupportedLanguages.zh_Hans,
    data: [
      "孟姜女的故事",
      "嫦娥奔月",
      "十二生肖的传说",
      "木兰辞",
      "井底之蛙",
      "孔融让梨",
      "神笔马良",
      "三只小猪",
      "龟兔赛跑",
      "大闹天宫",
    ],
  },
];
